### ISSUE TITLE
Incremental search example

### ISSUE THREAD

**Issue by petersn** [shnarazk/splr#212]
Hello,

Thanks for splr, it's proven comparably fast as cryptominisat and glucose on the instances I care about.

However, I'm having trouble figuring out how to use incremental search. I'd like to simply solve, then add more clauses, then solve again reusing the CDCL DB. Would it be possible to add an example to the docs explaining how to do this? Here's what I'm trying so far:

```rust
let mut solver = splr::solver::Solver::try_from((splr::Config::default(), base_instance)).unwrap();
match solver.solve() {
    ...
}
solver.add_var(); // Do this a few times
circuit_search_solver.add_clause(clause).unwrap(); // Do this a few times
```

I've also tried inserting `solver.reset()` before and after `.solve()`. I'm not sure exactly what `reset` is supposed to do.

Am I being silly, or missing something obvious?

**Comment by petersn** [comment]
Okay, I think I was just being silly, I think the issue was on my end. I suspect it still deserves a quick example in the docs, I'm still not sure how `.reset()` is supposed to be used.

**Comment by shnarazk** [comment]
Hi @petersn !
Ok, I'll add a note on incremental solver usage and merge it as 0.17.1. (There are certain demands on incremental solvers. Most issues from users were about incremental solver feature. ^^)
But actually I don't think Splr's implementation as an incremental solver is great. It's not optimal. If we use pre/inter-processors like 'clause subsumption(elimination)', it's difficult to return to, or build, a logically equivalent, intermediate state after finding a solution. So I need `reset`, which is the preparation to search from the ***initial*** formula with extra clauses...
